development:
  bucket: ardhiview-uploads
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
test:
  bucket: ardhiview-uploads
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: ardhiview-uploads
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
