development:
  bucket: ardhiview.user.files
  access_key_id: AKIAIKJINY5LG75XKLFQ
  secret_access_key: 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
test:
  bucket: ardhiview.user.files
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: ardhiview.user.files
  access_key_id: AKIAIKJINY5LG75XKLFQ
  secret_access_key: 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
